networks:
  loki:

services:
  loki:
    image: grafana/loki:3.2.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -log.level=debug -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      start_period: 20s
      interval: 10s
      timeout: 1s
      retries: 12  # try for 2 minutes

  promtail:
    image: grafana/promtail:3.2.0
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /mnt/c/Users/claudio/Downloads/EVB-510-053-180.txt:/mnt/EVB-510-053-180.txt:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: --inspect -log.level=debug -config.file=/etc/promtail/config.yml
    networks:
      - loki
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - "3000:3000"
    networks:
      - loki
    depends_on:
      - loki
      - promtail

volumes:
  loki_data:
